# Homebrew formula for BehalfID CLI (standalone binaries)
# Canonical tap: github.com/BehalfID/homebrew-tap
# Install: brew install BehalfID/tap/behalf
# Generated by scripts/release/render-homebrew-formula.mjs - do not hand-edit live tap copies.

class Behalf < Formula
  desc "Official CLI for BehalfID - agent permission management"
  homepage "https://behalfid.com"
  version "0.2.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.11/behalf-darwin-arm64.tar.gz"
      sha256 "2c857079d5227f7c66d5ab27fbc0b845c28ca2f2c7a9fd784a5a746c0085ca48"
    end
    on_intel do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.11/behalf-darwin-x64.tar.gz"
      sha256 "e1863c86c09e4521025b44524d1ccdfcb7e327c75a2c9e8e6c6ac40fbb2965c6"
    end
  end

  def install
    bin.install "behalf"
    bin.install_symlink "behalf" => "behalfid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/behalf --version")
    assert_match version.to_s, shell_output("#{bin}/behalfid --version")
  end
end
