# Homebrew formula for BehalfID CLI (standalone binaries)
# Canonical tap: github.com/BehalfID/homebrew-tap
# Install: brew install BehalfID/tap/behalf
# Generated by scripts/release/render-homebrew-formula.mjs - do not hand-edit live tap copies.

class Behalf < Formula
  desc "Official CLI for BehalfID - agent permission management"
  homepage "https://behalfid.com"
  version "0.2.15"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.15/behalf-darwin-arm64.tar.gz"
      sha256 "939b3ed9a31ddd308f313f43f63feca29310d14469a051bf9de94c9b7555fa3a"
    end
    on_intel do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.15/behalf-darwin-x64.tar.gz"
      sha256 "1507fdc37ce624d1e5ea3c93b9eb5d3ecd1b0e43314ea5977a8b651b4f756092"
    end
  end

  def install
    bin.install "behalf"
    bin.install_symlink "behalf" => "behalfid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/behalf --version")
    assert_match version.to_s, shell_output("#{bin}/behalfid --version")
  end
end
