# Homebrew formula for BehalfID CLI (standalone binaries)
# Canonical tap: github.com/BehalfID/homebrew-tap
# Install: brew install BehalfID/tap/behalf
# Generated by scripts/release/render-homebrew-formula.mjs - do not hand-edit live tap copies.

class Behalf < Formula
  desc "Official CLI for BehalfID - agent permission management"
  homepage "https://behalfid.com"
  version "0.2.14"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.14/behalf-darwin-arm64.tar.gz"
      sha256 "01ef846ea5cf3019a9e2094c016032e312062bd0ea88b81c80c35c6b5457c489"
    end
    on_intel do
      url "https://github.com/BehalfID/behalf/releases/download/v0.2.14/behalf-darwin-x64.tar.gz"
      sha256 "86a9bcba68faf7d325c94dc00eebc93219e7b4fa1a56844536c187240a336719"
    end
  end

  def install
    bin.install "behalf"
    bin.install_symlink "behalf" => "behalfid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/behalf --version")
    assert_match version.to_s, shell_output("#{bin}/behalfid --version")
  end
end
